### PR TITLE
Added Sound for JPro

### PR DESCRIPTION
**Pull request by FlorianKirmaier**
Made a library to replace the sound in JavaFX with a cross-platform implementation which also works with JPro.

I will probably soon add it to the demo page. :)

### CODE REVIEW

**Comment by HanSolo** [comment]
Are you aware of any problems related to jlink?

**Comment by FlorianKirmaier** [comment]
No, not really. 
According to the CI only the upload failed.
the build_app.sh also doesn't work on my MacBook.

**Comment by HanSolo** [comment]
Ok...will check next weekend and if it doesn't work I will create a jpro branch and merge it there.

**Comment by FlorianKirmaier** [comment]
I would guess that the GITHUB_TOKEN of the CI is missing, because it's based on my commits.

**Pull request merged**
